language: c
sudo: required

services:
  - docker

env:
  - ARCH=amd64 DISTRIBS=alpine
  - ARCH=amd64 DISTRIBS=jessie
  - ARCH=amd64 DISTRIBS=stretch

before_script:
  - make clean

script:
  - export TAG=${TRAVIS_TAG:-${TRAVIS_BRANCH}}
  - make
  - make images
  - make test

deploy:
  - provider: releases
    on:
      tags: true
      branch: master
    file_glob: true
    file:
      - build/s6rc-overlay-*.tar.*
      - build/manifest.txt
    skip_cleanup: true
    overwrite: true
    api_key:
      secure: "Ix04nfE+2Pulc3G21ZS9piTVPQtoa+N8RJKa80aUt0+sKxbd4QaScW9Y+oJHjzRgVPwqwUb8fBEiCwRKzZqHn1ubiEGlz7axlxo4ve3R4zd/SwTe2OKkrqQHPzb5Ng/sJBLtN7399a5uMAN3UJIdaDHWqm4NNNBXoHNh0kZObIs3rdMftsRJKC1PdSNbotbM3ZHuPn6Lk9hammpfHxD1BjSge8L5tMZ18I1TwIqEbIfO86S7lvIuxuS5u7bek5n9eHht5pmcBRF7WGc3/2mqMekz6HLWgfGoA1z1C949WOkyKi3F844/qfULqpm23uoFi86mlgeTK6uBLtn4SwnXrXhLgVa+e4Sff0jXzviqwwqZKfI+ocrL/PfBsLBf4eoK/30nFuk2hZoFrS11MKkk3FtiE9tg+QxWuMSvf8FlIkXFJ5Zq+1z/V7ztGbxw8dT2c72ERgtsNmX2900xtKSh5xCWEcEy8rn2m8Usiu5sp80mG3eTr8co798XtUqznHt9rSjOIebH8UeKz2JQeZxolhCUnB0+hRdzv9KAM9k1L2fca2eDuYqExnbrePzV4MeTPelvFH6g+47FJtJXNdjJIbwWezCtFu/yn71intPr6B7vBrjq3Igsox4KL53xG70oDUP8IhSozJsdblTT25uK0bbVrVA5VbtCllCbh/bniHA="
  - provider: script
    on:
      tags: true
      branch: master
    script: make push
    skip_cleanup: true

cache:
  directories:
    - .cache
    - build

# vim: expandtab sw=2 sts=2
