language: c
sudo: required

services:
  - docker

env:
  - ARCH=amd64 DISTRIBS=alpine
  - ARCH=amd64 DISTRIBS=jessie
  - ARCH=amd64 DISTRIBS=stretch

before_script:
  - make clean

script:
  - export TAG=${TRAVIS_TAG:-${TRAVIS_BRANCH}}
  - make
  - make images
  - make test

deploy:
  - provider: script
    on:
      tags: true
      branch: master
    script: make push
    skip_cleanup: true
  - provider: releases
    on:
      tags: true
      branch: master
    file_glob: true
    file:
      - build/s6rc-overlay-*.tar.*
      - build/manifest.txt
    skip_cleanup: true
    overwrite: true
    api_key:
      secure: "FEF2DTSfXuYFTpsAmIux2sA4CDCRzHEcb4sZxnIBwTGYcQA9JwAt0AjlzETwIRooi1o4w1YpyZ0eO4R+4asJqojwU5eAot75pweCQ3+YwYRY5Xi512ZG2UISU6Rz5i9oyGeoZz6tbamvQSMV3wwFmHz8YR8jtvGPghichRIp9utU1e0oPjNNfxctMQiDk1rFYvEHKRS7AsmQHmbS3QFgoJTf9q5a9m/YJnqzj7EfvcBU0rCLaoA5EHUppsUwMuumkqzF8V8KN0S7hkrAy9ilYFJ4eD/kj2PcCDqS2pfeCWHJHNtZQ7zIElaxbttEZ3VzBEGuuFBKLSYriVfeV0Ll25oQld+wZ3jz4Y581pqPTktKS8+IL1qe0GkMbJvUSSK19eLZjj2dq5M0e2YdvtetmzhjhQe56K8GRQ+YcJDh4M0mcEsgrDW9N88SQbN8ghh11fJgzcYSVQO9ipPJMJjBlAOzomRbn7SE7mRxImrsbFiJATPugIRwa1giYRXIeVAc8d5H0X/Zk0K/iouJZdNgcauhJPn8OSXTKFLwF8DAYBZVpEU4VhB0bTR9LHrqcz7tOkZk8HXJ5i97XpxF0nn7cBGrQ0BTUyg8UahQwEnzepwBaYx0D2exQowO/ROjEFRy4+AkFzPQXkMDlK4eWzLaHN4ukeLQZt/ltiFEyIZUzcM="

cache:
  directories:
    - .cache
    - build

# vim: expandtab sw=2 sts=2
