#!/bin/bash
cd $(dirname $0)
IMAGE="$1"
SLUG="$(echo $IMAGE | tr -s :/ __)"
LABEL="$2"
shift 2
if [[ $# -eq 0 ]]; then
    set -- [0-9]*/run
fi

for TST in "$@"; do
    DIR="${TST%%/run}"
    ../tools/printbanner "Test: $DIR"
    if
        if [[ -f "$DIR/Dockerfile" ]]; then
            DKFILE="$DIR/tmp-Dockerfile-$SLUG"
            TSTIMG="test-$SLUG"
            sed -e "/^FROM/s@-IMAGE-@$IMAGE@" "$DIR/Dockerfile" >"$DKFILE"
            docker build --label "$LABEL" -t "$TSTIMG" -f "$DKFILE" "$DIR"
            "$DIR/run" "$TSTIMG"
        else
            "$DIR/run" "$IMAGE"
        fi
    then
        ../tools/printbanner "$DIR: \e[32mPassed\e[0m"
    else
        ../tools/printbanner "$DIR: \e[31mFAILED !\e[0m"
        exit 1
    fi
done
