#!/bin/bash
set -e
set -x
IMAGE=$1

dotest() {
    local USR=$1 S6_USER=$2 UN=$3 GN=$4 _HOME=$5 OPTS="--rm"
    [[ -n $USR ]] && OPTS="$OPTS --user $USR"
    [[ -n $S6_USER ]] && OPTS="$OPTS -e S6_USER=$S6_USER"
    docker run $OPTS $IMAGE s6-logcmd sh -xc 's6-test `id -un` = '$UN' -a  `id -gn` = '$GN' -a $HOME = '$_HOME
}

dotest root ""   root root /root
dotest root foo  foo  foo  /home/foo

dotest foo root root  root  /root
dotest foo ""   foo foo /home/foo
