FROM alpine

ENV S6_VERBOSITY=1 \
    S6_CONF_DIR=/etc/s6-rc \
    S6_RUN_DIR=/run/s6-rc \
    S6_SERVICES_DIR=/etc/services.d \
    S6_INIT_TIMEOUT=500 \
    S6_START_TIMEOUT=120000 \
    S6_STOP_TIMEOUT=5000 \
    S6_TARGET=services

ADD archive.tar.bz2 /

ENTRYPOINT ["/sbin/container-init"]
