#!/bin/bash
set -bm
for sig in TERM HUP INT KILL; do
    ( exec docker run --rm -e 'S6_VERBOSITY=2' "$1" s6-logcmd sh -c "kill -$sig 1" ) & TEST=$!
    ( sleep 15 ; echo "Test timed out" >&2; exit 1 ) & TIMEOUT=$!

    wait -n
    RESULT=$?

    kill $TEST $TIMEOUT 2>/dev/null
    wait

    [[ $RESULT = 0 ]] || exit $RESULT
done
