#!/usr/bin/env bash
TARGET="$1"
ROOT="$2"
CACHE="$3"
OVERLAY="$4"
shift 4
set -ex

cp -a $OVERLAY $ROOT
cp $CACHE/gosu $ROOT/libexec/gosu
for A in $@; do tar xaf $A -C $ROOT; done
mkdir -p $ROOT/etc/services.d
setfacl -bR $ROOT || true
find $ROOT -type d | xargs chmod 0755
chmod 0500 $ROOT/sbin/*
chmod 0555 $ROOT/bin/* $ROOT/sbin/container-init
chmod -R a+rX $ROOT/etc/s6-rc $ROOT/libexec/s6-rc
chmod 0500 $ROOT/bin/s6-*uidgid
chmod 4555 $ROOT/libexec/gosu
tar caf $TARGET -C $ROOT --owner=0 --group=0 --exclude=.delete.me .

